[package]
name = "pathfinding"
description = "Pathfinding search library"
repository = "https://github.com/samueltardieu/pathfinding"
keywords = ["path-finding", "search", "shortest-path", "astar", "dijkstra"]
license = "Apache-2.0/MIT"
homepage = "https://rfc1149.net/devel/pathfinding.html"
documentation = "https://docs.rs/pathfinding/"
version = "0.1.17-pre"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
categories = ["algorithms"]
readme = "README.md"

[dependencies]
ndarray = { version = "0.10", optional = true }
num-traits = "0.1"

[dev-dependencies]
lazy_static = "0.2"

[features]
default = []
edmondskarp = ["ndarray"]

[package.metadata.docs.rs]
all-features = true
