[package]
name = "pathfinding"
description = "Pathfinding search library"
repository = "https://github.com/samueltardieu/pathfinding"
keywords = ["path-finding", "search", "shortest-path", "astar", "dijkstra"]
license = "Apache-2.0/MIT"
homepage = "https://www.rfc1149.net/devel/pathfinding.html"
documentation = "https://docs.rs/pathfinding/"
version = "0.1.1"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
num = "0.1"

[dev-dependencies]
lazy_static = "0.1"
