[package]
name = "pathfinding"
description = "Pathfinding search library"
repository = "https://github.com/samueltardieu/pathfinding"
keywords = ["path-finding", "search", "shortest-path", "astar", "dijkstra"]
license = "Apache-2.0/MIT"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
num = "0.1"
