[package]
name = "pathfinding"
description = "Pathfinding, flow, and graph algorithms"
repository = "https://github.com/samueltardieu/pathfinding"
keywords = ["shortest-path", "astar", "dijkstra", "flow", "graph"]
license = "Apache-2.0/MIT"
homepage = "https://rfc1149.net/devel/pathfinding.html"
documentation = "https://docs.rs/pathfinding/"
version = "0.1.19"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
categories = ["algorithms"]
readme = "README.md"

[dependencies]
ndarray = { version = "0.10", optional = true }
num-traits = "0.1"

[dev-dependencies]
lazy_static = "0.2"

[features]
default = ["edmondskarp", "kuhnmunkres"]
edmondskarp = ["ndarray"]
kuhnmunkres = ["ndarray"]

[package.metadata.docs.rs]
all-features = true

[badges]
appveyor = { repository = "samueltardieu/pathfinding" }
travis-ci = { repository = "samueltardieu/pathfinding" }
